version: '2.1'

services:
  storage-db:
    container_name: storage-db
    build: ./db
    restart: always
    volumes:
      - './db/init_scripts:/docker-entrypoint-initdb.d'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PWD}
      MONGO_INITDB_DATABASE: ${DB_DATABASE}
    command: --smallfiles
    ports:
      - 27017:27017
    healthcheck:
        test: exit 0
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PWD}
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_BASIC_PWD}
    links:
      - storage-db:mongo
  server-transpiler:
    build: ./server
    volumes_from:
      - server-data
    # typescript should watch the src directory
    command: tsc
    extends:
      file: server.base.yml
      service: base
  server-service:
    container_name: server-service
    build: ./server
    command: nodemon -w server/src/ server/src/index.js
    volumes_from:
      - server-data
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    extends:
      file: server.base.yml
      service: base
    depends_on:
      - storage-db
    links:
      - storage-db
      - mongo-express
  server-data:
    build: ./server
    volumes:
      - './server/src:/server'
    extends:
      file: server.base.yml
      service: base
    command: echo 'ok'